return {
  "saghen/blink.cmp",
  version = "1.*",
  opts = {
    keymap = { preset = "default" },
    appearance = {
      nerd_font_variant = "mono",
      kind_icons = {
        Text = "[Txt]",
        Method = "[Mthd]",
        Function = "[Func]",
        Constructor = "[Ctor]",
        Field = "[Fld]",
        Variable = "[Var]",
        Class = "[Cls]",
        Interface = "[Intf]",
        Module = "[Mod]",
        Property = "[Prop]",
        Unit = "[Unit]",
        Value = "[Val]",
        Enum = "[Enum]",
        Keyword = "[KW]",
        Snippet = "[Snip]",
        Color = "[Colr]",
        File = "[File]",
        Reference = "[Ref]",
        Folder = "[Dir]",
        EnumMember = "[EnumM]",
        Constant = "[Const]",
        Struct = "[Strt]",
        Event = "[Evt]",
        Operator = "[Op]",
        TypeParameter = "[TParam]",
      },
    },
    completion = { documentation = { auto_show = false } },
    sources = {
      default = { "lsp", "path", "buffer" },
    },
    fuzzy = { implementation = "prefer_rust_with_warning" },
  },
  opts_extend = { "sources.default" },
}
